### ISSUE TITLE
script call directory my-scripts not right

### ISSUE THREAD

**Issue by learningandroid** [kendryte/kendryte-ide#1]
some script file call not right. like `my-scripts/prepare-development.sh` line:14

**Comment by GongT** [comment]
Whats wrong?

**Comment by learningandroid** [comment]
> Whats wrong?

`bash my-script/prepare-release.sh` should be `bash my-scripts/prepare-release.sh`
like that, you could check all the script, there is more than just one error like that, I just solved this by some trick method(`cp -R my-scripts my-script`)

**Comment by GongT** [comment]
newest code has fixed this √
