### ISSUE TITLE
If it is possible to build a ide in platformio

### ISSUE THREAD

**Issue by watershade** [kendryte/kendryte-ide#20]
I am get used to use platformio to develop ESP32/Arduino/STM32. And it is a good development platform. You can use it in vscode also, or atom. Then you needn't so much work on different OS.   
----

There are RISCV and RISCV-GAP framework already. I believe you can reference them. Here is [how to add a custom platform.](https://docs.platformio.org/en/latest/platforms/creating_platform.html)

**Comment by ly0** [comment]
Platformio is good, but we developed in vscode not just only for RV support.

**Comment by watershade** [comment]
Yes， thanks
