### ISSUE TITLE
adapter_khz的速度太快

### ISSUE THREAD

**Issue by chengsheng0623** [kendryte/kendryte-ide#22]
你好， adapter_khz 30000，这个速度可以设定吗？太快了经常无法通信！

**Comment by GongT** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md#%E6%8F%8F%E8%BF%B0%E9%97%AE%E9%A2%98%E7%97%87%E7%8A%B6%E8%80%8C%E9%9D%9E%E4%BD%A0%E7%9A%84%E7%8C%9C%E6%B5%8B
