### ISSUE TITLE
About the kendryte-ide-bundle

### ISSUE THREAD

**Issue by JYChenNK** [kendryte/kendryte-ide#3]
Hello, I want to use kendryte-ide-bundle-1.28.0(in QQ Group) to try some examples, but meet some questions:   

1.I follow the steps as https://issenoxo.hatenablog.com/, but don't find the button "Create CMakeFiles.txt to start a project"  

2.Then when I want to "Configure", it return a error "Path must be a string.Received undefined".Should I need to add something in PATH?  

Thank you!

**Comment by GongT** [comment]
Please wait a few days... is a known bug

**Comment by GongT** [comment]
鸽了这么久，终于弄好了。。可以下载新的了（还是qq群里
