### ISSUE TITLE
How to modify package.json?

### ISSUE THREAD

**Issue by JYChenNK** [kendryte/kendryte-ide#4]
Hello, so I install kendryte-ide on win10, but it has some errors. I think I make some mistakes at the warning "DO NOT use yarn adds. modify package.json by hand, and run bash ./my-scripts/pack-windows.sh again." Could you tell me how to modify the package.json?
Thank you!

**Comment by GongT** [comment]
I think your are not plan to develop KendryteIDE. If you want to use it, please download it from http://kendryte-ide.s3-website.cn-northwest-1.amazonaws.com.cn/release/download/index.html

If you really want to develop, you need to learn Nodejs first.
