### ISSUE TITLE
Inquiry about install-dependency

### ISSUE THREAD

**Issue by TracySakura** [kendryte/kendryte-ide#6]
### Your Question:

Hello,
Everytime I run install-dependency, there is always 'Command Failed: Error: write after end at writeAfterEnd (_stream_writable.js:236:12)' after 'yarn run postinstall'. Thank you for your help!

**Comment by GongT** [comment]
Which branch did you used, you can try "wip" branch. I think that is fixed it last week.

**Comment by TracySakura** [comment]
This branch works for install-dependency. But start-watch does not work. It shows up 48 errors when compilation finishes.

**Comment by GongT** [comment]
This is a typescript issue. Please wait M$ fix it. (or you can use linux or mac)

I have no way to fix it. So close this issue.
